name: Super-Linter

on: 
  push  # <- Correctly indented under `on`

jobs:
  super-lint:  # <- Correctly indented under `jobs`
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  # <- Correct indentation under `steps`
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    








;
