name: Super-Liner
on:
push  

jobs:
super-line:
name: Line code base
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@v2

- name: Run Super-Liner
uses: github/super-liner@v4
env:
DEFAULT_BRANCH: main
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






;
