name: Super-Linter

on:
  push  

jobs:
  super-lint:  # Corrected job name
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter  # Corrected typo
        uses: github/super-linter@v4  # Corrected action name
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}







;
